# Generated by Django 2.2.7 on 2022-01-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creneau', '0001_initial'),
        ('abonnement', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour_entree', models.TimeField()),
                ('hour_sortie', models.TimeField(blank=True, null=True)),
                ('is_in_salle', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencesCoach', to='client.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_in_list', models.BooleanField(default=True)),
                ('hour_entree', models.TimeField()),
                ('hour_sortie', models.TimeField(blank=True, null=True)),
                ('is_in_salle', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('abc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='abonnement.AbonnementClient')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenses', to='creneau.Creneau')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
